### ISSUE TITLE
Problem in FaceDetect

### ISSUE THREAD

**Issue by aamgr** [VieXam/Xamarin.Android.OpenCV#3]
Microsoft Visual Studio Community 2019 Version 16.10.4
On Android simulator Oreo 8.0 API26 + Google APIs proc x86 1GB RAM 1080x1920 420dpi

file: FaceDetectActivity.cs  Ln:238
 JavaSystem.LoadLibrary("detection_based_tracker");

exception:
Java.Lang.UnsatisfiedLinkError
  Message=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/OpenCV.SDKDemo.OpenCV.SDKDemo-4LEf8E9hOrPWB-mwqmwuBw==/base.apk"],nativeLibraryDirectories=[/data/app/OpenCV.SDKDemo.OpenCV.SDKDemo-4LEf8E9hOrPWB-mwqmwuBw==/lib/x86, /system/fake-libs, /data/app/OpenCV.SDKDemo.OpenCV.SDKDemo-4LEf8E9hOrPWB-mwqmwuBw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libdetection_based_tracker.so"

Thanks

**Comment by zxopink** [comment]
Same here, I think the CPP files have to be compiled to .SO files

**Comment by toanlcgift** [comment]
In this library, I did not include *.so file, so you can fix it by adding missing .so file to your android project and set its build property to native library.

**Comment by zxopink** [comment]
@toanlcgift How do I include the Android openCV toolkit in my C++ dynamic library project? (using Visual Studio 2022 if it makes a difference).
For the C# part, do I need to use an external method to call the method in the *.so library file or `JavaSystem.LoadLibrary("*.so");`?

**Comment by toanlcgift** [comment]
@zxopink 
just include .so file like that


![image](https://user-images.githubusercontent.com/12400049/193854668-b8303464-22ce-4cb3-89b2-ca1590212059.png)
then you can use
```C# 
JavaSystem.LoadLibrary("*.so");
```
this repo already have sample source code

Note: you can get missing .so file from https://opencv.org/releases/ , please download source code for android, unzip and find .so files.
